### ISSUE TITLE
Keys missing: Notice: Undefined variable: key in WP_CLI/DotenvCommand.php on line 281

### ISSUE THREAD

**Issue by unematiii** [aaemnnosttv/wp-cli-dotenv-command#10]
Im getting bunch of warnings about the missing 2nd argument:

`Missing argument 2 for WP_CLI_Dotenv\WP_CLI\DotenvCommand::WP_CLI_Dotenv\WP_CLI\{closure}() in /Users/.../vendor/aaemnnosttv/wp-cli-dotenv-command/src/WP_CLI/DotenvCommand.php on line 280`

I've traced this back to `Illuminate/Support/Collection`, where fn `each` simply wraps `array_map`, that doesn't supply key values to the callback. This has been replaced with a simple loop over items in newer versions of `Illuminate/Support/Collection` and that change does not seem to be part of `tightenco/collect 5.2.*` .

**Comment by aaemnnosttv** [comment]
The command isn't compatible with the breaking changes to the Collection package in 5.3. (See ccf025363e9354c8a1126071a30e5cdccc7a3c63).

You might try doing a fresh install of the dotenv command package and see if that clears things up for you?

**Comment by unematiii** [comment]
Umm, yeah, I was misled. Seems a namespace clash with https://github.com/tareq1988/wp-eloquent.

**Comment by aaemnnosttv** [comment]
Ah ok. Are you requiring the wp-cli command into your project or installing via the `wp package` command?

**Comment by unematiii** [comment]
I have 

```
require:
  - ./vendor/autoload.php

```
in wp-cli.yml

which is probably the root cause... I should bootstrap all commands separately?

**Comment by unematiii** [comment]
I removed a dependency for `req1988/wp-eloquent` and this also cleared extra Illuminate packages - now everything works! Think I can live without the ORM interface for the time being.

**Comment by aaemnnosttv** [comment]
It sounds like you're using the older installation method, (pre wp-cli 0.23) but at the project level as well.

Try this:
- Remove the wp-cli-dotenv-command from your project.
- Install the package with wp-cli globally:
```
wp package install aaemnnosttv/wp-cli-dotenv-command:^1.0
```

You should have no more conflict!

**Comment by unematiii** [comment]
Hi!

Thx for advice! However, I would actually like to install all commands per project basis only (some of my teammates do not want WP specific stuff in their machines permanently) and would like the WP-CLI to automatically find them.

Maybe a separate composer.json (and hence vendor)? But that would still limit my options to make use of the aformentioned ORM interface inside commands.

**Comment by aaemnnosttv** [comment]
Are you also then installing wp-cli at the project level?

**Comment by aaemnnosttv** [comment]
Closing this for now as it seems to be mostly an issue with installation at the project level.
