### ISSUE TITLE
PHP 7.2 support?

### ISSUE THREAD

**Issue by bumTomica** [aaemnnosttv/wp-cli-dotenv-command#15]
As you can see, please check for PHP 7.2 support. Thank you!

`PHP Fatal error:  Uncaught TypeError: Argument 2 passed to WP_CLI_Dotenv\Dotenv\FileLines::WP_CLI_Dotenv\Dotenv\{closure}() must implement interface WP_CLI_Dotenv\Dotenv\LineInterface, integer given in /Users/bumtomica/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-dotenv-command/src/Dotenv/FileLines.php:99
Stack trace:
#0 [internal function]: WP_CLI_Dotenv\Dotenv\FileLines->WP_CLI_Dotenv\Dotenv\{closure}(Object(WP_CLI_Dotenv\Dotenv\KeyValue), 0)
#1 /Users/bumtomica/.composer/vendor/tightenco/collect/src/Collect/Support/Arr.php(175): call_user_func(Object(Closure), Object(WP_CLI_Dotenv\Dotenv\KeyValue), 0)
#2 /Users/bumtomica/.composer/vendor/tightenco/collect/src/Collect/Support/Collection.php(673): Tightenco\Collect\Support\Arr::first(Array,Object(Closure), Object(stdClass))
#3 /Users/bumtomica/.composer/vendor/tightenco/collect/src/Collect/Support/Collection.php(257): Tightenco\Collect\Support\Collection->first(Object(Closure), Object(stdClass))
#4 /Users/bumtomica/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-dotenv-command/src/ in /Users/bumtomica/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-dotenv-command/src/Dotenv/FileLines.php on line 99`

**Comment by aaemnnosttv** [comment]
Hi there 👋 

The library has supported PHP 7.2 for quite a while now and runs tests against it regularly (https://travis-ci.org/aaemnnosttv/wp-cli-dotenv-command/builds/439503253).

It seems as though you're not running the latest version as the Collect library was removed in 2.0.

Please update to the latest and let me know if you're still seeing any problems.

**Comment by bumTomica** [comment]
Interesting. I'm running latest "wp-cli/wp-cli-bundle" as pointed here (package command was not working in new version). Not a heavy wp-cli user so keep that in mind :)

https://github.com/wp-cli/wp-cli/issues/4900

**Comment by aaemnnosttv** [comment]
Ah, ok. If you're running the latest wp-cli bundle now then you should have access to the `package` command again. 

To update to the latest version of the `dotenv` command, try `wp package install aaemnnosttv/wp-cli-dotenv-command`, and see if that does it for you.

**Comment by aaemnnosttv** [comment]
Closing this as a dependency conflict with an older version.
