### ISSUE TITLE
`salts generate` will badly trims existing values if not quoted

### ISSUE THREAD

**Issue by redgluten** [aaemnnosttv/wp-cli-dotenv-command#20]
Using `salts generate` (or `regenerate` on a `.env` file with unquoted values results in badly trimmed values for all settings.

For example:

```
DB_NAME=my_db
DB_USER=my_user
...
```

will result in:

```
DB_NAME='y_d'
DB_USER='y_use'
```

I realize quoting your values is now considered good practice but some generators like WP-Cli Valet command don’t do it all the time. I’ll also open an issue there.

**Comment by aaemnnosttv** [comment]
You're likely using an old version of the package as new salts are currently set with a wrapping single quote. Please update to the latest version and let me know if this is still an issue for you.

**Comment by redgluten** [comment]
You’re right, see my [PR](https://github.com/aaemnnosttv/wp-cli-dotenv-command/pull/22) for why I had the wrong version.
