### ISSUE TITLE
Warnings with salts generate

### ISSUE THREAD

**Issue by redgluten** [aaemnnosttv/wp-cli-dotenv-command#21]
When using salts generate I got some php warnings:

```
PHP Warning:  Declaration of WP_CLI_Dotenv\Dotenv\FileLines::add(WP_CLI_Dotenv\Dotenv\LineInterface $line) should be compatible with Illuminate\Support\Collection::add($item) in /Users/admin/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-dotenv-command/src/Dotenv/FileLines.php on line 186

Warning: Declaration of WP_CLI_Dotenv\Dotenv\FileLines::add(WP_CLI_Dotenv\Dotenv\LineInterface $line) should be compatible with Illuminate\Support\Collection::add($item) in /Users/admin/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-dotenv-command/src/Dotenv/FileLines.php on line 186
```

**Comment by aaemnnosttv** [comment]
Looks like you're using an older version of the package as it no longer has any dependencies as of [v2.0](https://github.com/aaemnnosttv/wp-cli-dotenv-command/releases/tag/v2.0.0) which is already over a year old.

Please update your installed version of the package and let me know if you have any further issues!

**Comment by redgluten** [comment]
I indeed had an older version, it works with the current one. Closed.
