### ISSUE TITLE
Search() ignores commented lines.

### ISSUE THREAD

**Issue by Levdbas** [aaemnnosttv/wp-cli-dotenv-command#23]
Thanks a bunch for this plugin!

When using the set command and the variable exist but is commented out, a new line is placed at the end of the .env file.

In the framework I use, lines are commented out like this `# DB_HOST=localhost`.
It would be nice if the `search()` function used by `set()` would also search for the needle with the prefix of `#` and `# `.

**Comment by aaemnnosttv** [comment]
Hey thanks for the suggestion! I see how this could be useful, although I don't think that it should happen automatically as that could have unintended consequences. This could be potentially enabled with a flag when running the command, and then you could also set that to the default using your `wp-cli.yml` config if you really wanted.

Let me know what you think?

**Comment by Levdbas** [comment]
Sounds like a good idea! Maybe the command `set VAR --includecomments` ?

**Comment by aaemnnosttv** [comment]
After thinking about this a bit more, I've decided not to add support for this as it would be a bit more complicated than simply adding a flag to include them.

Thanks again for the suggestion! 🙂
