### ISSUE TITLE
Doesn't recognise my PHP 8.0.9

### ISSUE THREAD

**Issue by MeonValleyWeb** [aaemnnosttv/wp-cli-dotenv-command#26]
- aaemnnosttv/wp-cli-dotenv-command dev-master requires php ^5.6 | ^7.0 -> your php version (8.0.9) does not satisfy that requirement.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
---
Error: Package installation failed (Composer return code 2).
Reverted composer.json.

**Comment by aaemnnosttv** [comment]
Hi there! It sounds like the wp-cli package repo isn't giving you the latest version which is a bit of a known issue. You can see the current `dev-master` does support PHP 8 here: https://packagist.org/packages/aaemnnosttv/wp-cli-dotenv-command#dev-master

I'll reach out to the wp-cli team to see if they can help. In the meantime you should be able to upgrade it like so:

```
cd ~/.wp-cli/packages
composer config repos.wp-cli --unset
composer update aaemnnosttv/wp-cli-dotenv-command
```

The change from the second command there will be undone next time you use the `wp package` command, but you could always put it back with `composer config repos.wp-cli composer https://wp-cli.org/package-index/`

Let me know if that does it for you 👍

**Comment by MeonValleyWeb** [comment]
Hi, gave that a whirl and got:


  `Problem 1
    - illuminate/container v5.6.39 requires php ^7.1.3 -> your php version (8.0.9) does not satisfy that requirement.
    -     - aaemnnosttv/wp-cli-valet-command dev-master requires illuminate/container >=5.1 <5.7 -> satisfiable by illuminate/container[v5.6.39].
    - aaemnnosttv/wp-cli-valet-command is locked to version dev-master and an update of this package was not requested.`

Have done a composer global update and nothing needed updating

**Comment by MeonValleyWeb** [comment]
Reinstalled wp-cli and your commands ran fine:

`composer update aaemnnosttv/wp-cli-dotenv-command
Loading composer repositories with package information
Package "aaemnnosttv/wp-cli-dotenv-command" listed for update is not locked.
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files`

But still then getting the original error on installing dotenv..

**Comment by aaemnnosttv** [comment]
@LarkRiseMedia it should be good now – would you please try the same thing again?

**Comment by MeonValleyWeb** [comment]
Had a go and tried to install it again using the commands above and re-ran and got this.

`Installing package aaemnnosttv/wp-cli-dotenv-command (^2.0)
Updating /Users/andrew/.wp-cli/packages/composer.json to require the package...
Updating package index repository url...
Using Composer to install the package.`

`Loading composer repositories with package information
Updating dependencies
Generating rules
Resolving dependencies through SAT
Looking at all rules.`

`Dependency resolution completed in 0.000 seconds
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - Root composer.json requires aaemnnosttv/wp-cli-dotenv-command ^2.0 -> satisfiable by aaemnnosttv/wp-cli-dotenv-command[v2.0.0].
    - aaemnnosttv/wp-cli-dotenv-command v2.0.0 requires php ^5.6 | ^7.0 -> your php version (8.0.10) does not satisfy that requirement.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

Error: Package installation failed (Composer return code 2).
Reverted composer.json.`

**Comment by aaemnnosttv** [comment]
By the looks of your output there, it seems like you ran `wp package install` rather than using composer directly which is an important detail.

> Updating package index repository url...

This is something the package command does if it detects the main package index is missing, which is why we need to run it via composer directly instead. So even if you remove it before running the package command (as shown above) it will still try to install the old version of the package because it restores the WP-CLI composer repository URL on the fly before running composer.

**Comment by aaemnnosttv** [comment]
This is now fixed upstream 🎉  See https://github.com/wp-cli/package-index/pull/121

You should now be able to install/update the package as usual using the `wp package` commands 👍
