### ISSUE TITLE
Deprecation notice

### ISSUE THREAD

**Issue by martingreenwood** [aaemnnosttv/wp-cli-dotenv-command#27]
Hi Guys

When running this in Laraval Valet on PHP 8.2.7 you get the following error:

`Deprecated: Return type of WP_CLI_Dotenv\Dotenv\Collection::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/martingreenwood/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-dotenv-command/src/Dotenv/Collection.php on line 186

Deprecated: Return type of WP_CLI_Dotenv\Dotenv\Collection::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/martingreenwood/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-dotenv-command/src/Dotenv/Collection.php on line 202

Deprecated: Return type of WP_CLI_Dotenv\Dotenv\Collection::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/martingreenwood/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-dotenv-command/src/Dotenv/Collection.php on line 221

Deprecated: Return type of WP_CLI_Dotenv\Dotenv\Collection::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/martingreenwood/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-dotenv-command/src/Dotenv/Collection.php on line 237

Deprecated: Return type of WP_CLI_Dotenv\Dotenv\Collection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/martingreenwood/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-dotenv-command/src/Dotenv/Collection.php on line 249

Deprecated: Return type of WP_CLI_Dotenv\Dotenv\Collection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/martingreenwood/.wp-cli/packages/vendor/aaemnnosttv/wp-cli-dotenv-command/src/Dotenv/Collection.php on line 80`

**Comment by aaemnnosttv** [comment]
Thanks for the report! I've gone ahead and updated master with updates to bring things up to date. If you're using `dev-master` you should be able to update now otherwise I'll tag a new version soon 👍

**Comment by ethanclevenger91** [comment]
@aaemnnosttv any chance we'll see that new version tagged?
