### ISSUE TITLE
Consider adding functional tests to this project

### ISSUE THREAD

**Issue by danielbachhuber** [aaemnnosttv/wp-cli-dotenv-command#3]
Functional tests are an integral ingredient of highly-quality, maintainable commands. WP-CLI tries to make it as easy as possible to add functional tests to your package with its `wp scaffold package-tests` command:

https://github.com/wp-cli/scaffold-package-command#wp-scaffold-package-tests

I'd encourage you to consider adding functional tests to your package :) By starting your functional tests early on, it also makes it much easier to maintain your project over time.

**Comment by aaemnnosttv** [comment]
Yeah, I've been meaning to try that out.  I will add these for sure, just a matter of time :)

**Comment by aaemnnosttv** [comment]
Having a pretty rough start so far.  wp-cli/scaffold-package-command#19
