### ISSUE TITLE
Package is locking old version of collect

### ISSUE THREAD

**Issue by derkjn** [aaemnnosttv/wp-cli-dotenv-command#9]
When installing this package, the latest version of `collect` required is `5.2.*`, while the latest published is `5.3.*`.

Can you please update the `composer.json`?

**Comment by aaemnnosttv** [comment]
I'm afraid it's not as simple updating the composer.json. Laravel (the source of the collect package) does not adhere to "standard" semantic versioning. Instead, 5.2 to 5.3 is considered a major update, and in this case, actually includes breaking changes that affect the collect package.

Originally, [I had a looser restriction on the package version](https://github.com/aaemnnosttv/wp-cli-dotenv-command/commit/ccf025363e9354c8a1126071a30e5cdccc7a3c63), but had to pull it back for this reason.

If it's going to cause problems, then I will probably need to replace collect with something else.

**Comment by derkjn** [comment]
I see your point, I'm currently using collection at 5.3 as 5.2 has some issues when performing searches (returning empty sets even though matching elements are actually in the collection) and `wp-cli-dotenv` on `1.0.1` replaces the first and the last characters in the variables when running the `set` command!
I'll see if I can find a workaround for the bug in collection 5.2.

Cheers!

**Comment by aaemnnosttv** [comment]
Yeah, `1.0.1` broke when installing the command after Laravel 5.3 was released because of the looser version constraint.

See here https://github.com/aaemnnosttv/wp-cli-dotenv-command/compare/v1.0.1...v1.0.2

How are you installing the command? Is there another wp-cli package that uses collect?

**Comment by derkjn** [comment]
It's all configured in the deployment script when running the initial `composer install`, from a bedrock installation.
Collect is currently used in other libraries and in the theme I'm developing, I can quite easily work around that, although it would be nice to have the latest version here too :)
What was the breaking change for this command? Unfortunately I'm not too expert with the wp cli commands yet but I'd love to dig more into the code and see if I can help you fix it up :)

**Comment by aaemnnosttv** [comment]
I wouldn't install this package as part of your project. You can install it globally on the server using 

```
wp package install aaemnnosttv/wp-cli-dotenv-command:^1.0
```

That will allow you to remove it from your project's composer.json and clear up the conflict in the process.

**Comment by derkjn** [comment]
Thanks for your help, I installed the package globally on the server and removed the dependencies from the project, everything works like a charm!
Thank you for your support!
